apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645p31-deployment
  labels: {app.kubernetes.io/managed-by: graphite-jenkins-gke}
spec:
  replicas: 1
  selector:
    matchLabels: {app: swe645p31}
  template:
    metadata:
      labels: {app: swe645p31}
    spec:
      containers:
      - name: swe645p31
        image: swe645aspsr/ui
        ports:
        - name: port4420
          containerPort: 4420
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: swe645p31-service
  labels: {app.kubernetes.io/managed-by: graphite-jenkins-gke}
spec:
  ports:
    - name: angular
      protocol: TCP
      port: 4297
      targetPort: 4200
  selector: {app: swe645p31}
  type: LoadBalancer
